### ISSUE TITLE
Is Customizable for Hololens Platform

### ISSUE THREAD

**Issue by krishnabhaskar** [TylerWargo/Virtual-Feelality#1]
Hi Tyler, Can this project be customized for Microsoft Hololens platfrom using Unity.
If yes, what needs to be done. Please have a look and let me know.
Thanks Krishna

**Comment by TylerWargo** [comment]
**Hey krishnabhaskar,**

Apologies for the late response, but glad to be fortunate to do so now. On the issue of Hololens support. Currently, this project is using only LeapMotion tracking to detect fingers, and LeapMotion does not officially support them as there is no way to attach the sensor to the device itself.

**I do not own a Hololens development kit, so myself adding support is not foreseen at this current point in time.** Tracking for other platforms such as the HTC Vive and Oculus Rift should be coming soon, with multiple ways of tracking such as the Vive Tracker and more.

Best regards,
Tyler Wargo
